### ISSUE TITLE
HATES ascii

### ISSUE THREAD

**Issue by esacteksab** [sigmavirus24/github-cli#14]
```
✗ gh gist 2995997    
https://gist.github.com/2995997: Sublime Text 2 - Useful Shortcuts
Traceback (most recent call last):
  File "/home/bmorriso/.virtualenvs/github-cli/bin/gh", line 8, in <module>
    load_entry_point('gh-cli==0.1.b', 'console_scripts', 'gh')()
  File "/home/bmorriso/.virtualenvs/github-cli/local/lib/python2.7/site-packages/gh_cli-0.1.b-py2.7.egg/gh/main.py", line 29, in main
    status = commands[command].run(opts, args[1:])
  File "/home/bmorriso/.virtualenvs/github-cli/local/lib/python2.7/site-packages/gh_cli-0.1.b-py2.7.egg/gh/commands/gist/__init__.py", line 27, in run
    print('{0.filename}\n{0.content}\n'.format(f))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u21e7' in position 305: ordinal not in range(128)
```

**Comment by sigmavirus24** [comment]
Yep. Strings basically suck in Python. ;)

In a side-note we can totally figure out a good way of working around this.

**Comment by esacteksab** [comment]
well my puppy self has sort of figured this much out
https://gist.github.com/esacteksab/1602f7cd5162a3161c03

**Comment by esacteksab** [comment]
https://twitter.com/KCombinator/status/385580686742020096
https://twitter.com/KCombinator/status/385580826492030976

**Comment by esacteksab** [comment]
https://twitter.com/nriley/status/385583740832841729

Link from above Tweet -- just in case https://wiki.python.org/moin/PrintFails
