### ISSUE TITLE
Test failure (test_format_short_issue (test_issues.TestIssueLsCommand)) but tox still succeeds

### ISSUE THREAD

**Issue by msabramo** [sigmavirus24/github-cli#15]
`run_tests.py` probably not returning a proper exit status. Looking at it...

```
$ tox -e py27
GLOB sdist-make: /Users/marca/dev/git-repos/github-cli/setup.py
py27 inst-nodeps: /Users/marca/dev/git-repos/github-cli/.tox/dist/gh-cli-0.1.b.zip
py27 runtests: PYTHONHASHSEED='1327256247'
py27 runtests: commands[0] | python run_tests.py
.......A valid integer is required
.E......
======================================================================
ERROR: test_format_short_issue (test_issues.TestIssueLsCommand)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marca/dev/git-repos/github-cli/tests/test_issues.py", line 40, in test_format_short_issue
    out = self.command.format_short_issue(self.issue)
  File "/Users/marca/dev/git-repos/github-cli/gh/commands/issue/ls.py", line 75, in format_short_issue
    return (self.fs.format(issue, bold=tc['bold'], default=tc['default'])
ValueError: Invalid conversion specification

----------------------------------------------------------------------
Ran 15 tests in 5.678s

FAILED (errors=1)
___________________________________________________________________________________ summary ____________________________________________________________________________________
  py27: commands succeeded
  congratulations :)
```

**Comment by msabramo** [comment]
https://github.com/sigmavirus24/github-cli/pull/16 fixes the issue that tox reports success even when some tests fail.

**Comment by msabramo** [comment]
#17 fixes the failing test

**Comment by msabramo** [comment]
Travis CI tests are currently failing because of the test failure that is fixed by #17:

https://travis-ci.org/sigmavirus24/github-cli/jobs/40092872
